# Generated by Django 5.2.5 on 2025-09-22 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_attendance_created_at_attendance_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='general_average',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='pre_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
