# Generated by Django 5.2.5 on 2025-09-24 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_grade_general_average_grade_pre_final'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(auto_now_add=True)),
                ('illness', models.CharField(db_index=True, max_length=255)),
                ('treatment', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('attended_by', models.CharField(blank=True, max_length=100, null=True)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_visits', to='students.student')),
            ],
            options={
                'ordering': ['-visit_date'],
                'indexes': [models.Index(fields=['illness'], name='students_cl_illness_a9e051_idx'), models.Index(fields=['visit_date'], name='students_cl_visit_d_64d484_idx')],
            },
        ),
    ]
