# Generated by Django 5.2.5 on 2025-10-14 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_clinicvisit'),
    ]

    operations = [
        migrations.CreateModel(
            name='BehaviorRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('behavior_type', models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative')], db_index=True, max_length=50)),
                ('category', models.CharField(choices=[('Tardiness', 'Tardiness'), ('Bullying', 'Bullying'), ('Disrespect', 'Disrespect'), ('Outstanding Performance', 'Outstanding Performance'), ('Other', 'Other')], db_index=True, max_length=100)),
                ('description', models.TextField()),
                ('action_taken', models.TextField(blank=True, null=True)),
                ('reported_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_records', to='students.student')),
            ],
            options={
                'ordering': ['-date', 'student__last_name', 'student__first_name'],
                'indexes': [models.Index(fields=['date'], name='students_be_date_756323_idx'), models.Index(fields=['behavior_type'], name='students_be_behavio_cb5623_idx'), models.Index(fields=['category'], name='students_be_categor_2c4695_idx')],
            },
        ),
    ]
