# Generated by Django 5.2.5 on 2025-10-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_behaviorrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='quarter',
            field=models.CharField(choices=[('1st', '1st Quarter'), ('2nd', '2nd Quarter'), ('3rd', '3rd Quarter'), ('4th', '4th Quarter')], db_index=True, default='1st', max_length=10),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['quarter'], name='students_at_quarter_fa1245_idx'),
        ),
    ]
