# Generated by Django 5.2.5 on 2025-10-15 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_attendance_quarter_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='attendance',
            name='students_at_quarter_fa1245_idx',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='quarter',
        ),
    ]
