# Generated by Django 5.2.5 on 2025-10-17 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_alter_attendance_unique_together_attendance_quarter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behaviorrecord',
            name='date',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
    ]
