# Generated by Django 5.2.5 on 2025-10-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_student_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(db_index=True),
        ),
    ]
