# Generated by Django 5.2.5 on 2025-10-20 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_alter_attendance_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attendance',
            new_name='AttendanceRecord',
        ),
        migrations.RenameIndex(
            model_name='attendancerecord',
            new_name='students_at_date_ad4af7_idx',
            old_name='students_at_date_895989_idx',
        ),
        migrations.RenameIndex(
            model_name='attendancerecord',
            new_name='students_at_quarter_9566a5_idx',
            old_name='students_at_quarter_fa1245_idx',
        ),
        migrations.RenameIndex(
            model_name='attendancerecord',
            new_name='students_at_status_d4ab0b_idx',
            old_name='students_at_status_90671f_idx',
        ),
        migrations.AlterModelTable(
            name='attendancerecord',
            table='students_attendancerecord',
        ),
    ]
