# Generated by Django 5.2.5 on 2025-10-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_rename_attendance_attendancerecord_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('school_year', models.CharField(help_text='e.g., 2024-2025', max_length=20)),
                ('grade', models.CharField(help_text='e.g., 7, 8, 9, 10', max_length=10)),
                ('adviser_name', models.CharField(max_length=255)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['school_year', 'grade', 'name'],
                'unique_together': {('name', 'school_year', 'grade')},
            },
        ),
    ]
