# Generated by Django 5.2.5 on 2025-10-27 13:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_section'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('student', 'school_year', 'subject')},
        ),
        migrations.AddField(
            model_name='grade',
            name='is_finalized',
            field=models.BooleanField(default=False, help_text='If True, this grade record cannot be edited or deleted.'),
        ),
        migrations.AddField(
            model_name='student',
            name='general_average',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='school_year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='behaviorrecord',
            name='category',
            field=models.CharField(choices=[('Tardiness', 'Tardiness'), ('Bullying', 'Bullying'), ('Disrespect', 'Disrespect'), ('Cutting Classes', 'Cutting Classes'), ('Vandalism', 'Vandalism'), ('Cheating', 'Cheating'), ('Leadership', 'Leadership'), ('Participation', 'Participation'), ('Helping Others', 'Helping Others'), ('Outstanding Performance', 'Outstanding Performance'), ('Other', 'Other')], db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='behaviorrecord',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='pre_final',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Calculated final rating for this subject based on quarters', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='q1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='grade',
            name='q2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='grade',
            name='q3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='grade',
            name='q4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='section',
            name='adviser_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='grade',
            field=models.CharField(choices=[('7', 'Grade 7'), ('8', 'Grade 8'), ('9', 'Grade 9'), ('10', 'Grade 10')], db_index=True, help_text='Grade level', max_length=2),
        ),
        migrations.AlterField(
            model_name='section',
            name='school_year',
            field=models.CharField(db_index=True, help_text='e.g., 2024-2025', max_length=9),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardian_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.CharField(max_length=50),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['is_finalized'], name='students_gr_is_fina_bba6bf_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['school_year'], name='students_se_school__4f41da_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['grade'], name='students_se_grade_c8e4e3_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['name'], name='students_se_name_0c0ce1_idx'),
        ),
        migrations.RemoveField(
            model_name='grade',
            name='general_average',
        ),
    ]
