# Generated by Django 5.2.5 on 2025-10-28 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='allowed_subjects',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='allowed_subjects',
            field=models.ManyToManyField(blank=True, help_text="Select the subjects this teacher can manage grades for. Only applies if role is 'teacher'.", related_name='teachers', to='students.subject'),
        ),
    ]
