# Generated by Django 5.2.5 on 2025-10-28 15:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_subject_remove_userprofile_allowed_subjects_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='allowed_subjects',
        ),
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='students.section'),
        ),
        migrations.CreateModel(
            name='TeacherClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(db_index=True, help_text='e.g., 2024-2025', max_length=9)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='students.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='students.subject')),
                ('teacher', models.ForeignKey(help_text='The teacher assigned to this class.', limit_choices_to={'profile__role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='classes_taught', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher Class Assignment',
                'verbose_name_plural': 'Teacher Class Assignments',
                'ordering': ['academic_year', 'section__grade', 'section__name', 'subject__name'],
                'unique_together': {('subject', 'section', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('q2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('q3', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('q4', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('pre_final', models.DecimalField(blank=True, decimal_places=2, help_text='Calculated final rating for this subject based on quarters', max_digits=5, null=True)),
                ('is_finalized', models.BooleanField(default=False, help_text='If True, this grade record cannot be edited or deleted.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student')),
                ('teacher_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.teacherclass')),
            ],
            options={
                'ordering': ['student__last_name', 'teacher_class__subject__name'],
            },
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['is_finalized'], name='students_en_is_fina_779fab_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'teacher_class')},
        ),
    ]
