# Generated by Django 5.2.5 on 2025-10-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_remove_section_subject_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='behaviorrecord',
            name='students_be_behavio_cb5623_idx',
        ),
        migrations.RemoveField(
            model_name='behaviorrecord',
            name='behavior_type',
        ),
        migrations.AddField(
            model_name='behaviorrecord',
            name='offense_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='behaviorrecord',
            name='offense_type',
            field=models.CharField(default='Minor', max_length=10),
        ),
        migrations.AlterField(
            model_name='behaviorrecord',
            name='action_taken',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='behaviorrecord',
            name='category',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='behaviorrecord',
            name='date',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
    ]
