# Generated by Django 5.2.5 on 2025-10-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0021_remove_behaviorrecord_students_be_behavio_cb5623_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='elementary_gen_ave',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='e.g., 88.75', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='elementary_school',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='elementary_school_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='elementary_school_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='name_extension',
            field=models.CharField(blank=True, help_text='e.g., Jr., Sr., III', max_length=10, null=True),
        ),
    ]
