# Generated by Django 5.2.5 on 2025-10-30 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0022_student_elementary_gen_ave_student_elementary_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('registrar', 'Registrar'), ('nurse', 'Nurse'), ('guidance_counselor', 'Guidance Counselor'), ('admin', 'Admin')], default='teacher', max_length=20),
        ),
    ]
