# Generated by Django 5.2.5 on 2025-10-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0023_alter_userprofile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1_open', models.BooleanField(default=True, help_text='Is Quarter 1 grade entry open for teachers?')),
                ('q2_open', models.BooleanField(default=False, help_text='Is Quarter 2 grade entry open for teachers?')),
                ('q3_open', models.BooleanField(default=False, help_text='Is Quarter 3 grade entry open for teachers?')),
                ('q4_open', models.BooleanField(default=False, help_text='Is Quarter 4 grade entry open for teachers?')),
            ],
            options={
                'verbose_name': 'Grade Lock Setting',
                'verbose_name_plural': 'Grade Lock Settings',
            },
        ),
    ]
