# Generated by Django 5.2.5 on 2025-10-31 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0024_gradesettings'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='teacher_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.teacherclass'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('teacher_class', 'student', 'date')},
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['teacher_class'], name='students_at_teacher_a1ddee_idx'),
        ),
    ]
