# Generated by Django 5.2.5 on 2025-10-31 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0025_alter_attendancerecord_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicvisit',
            name='follow_up_required',
        ),
    ]
