# Generated by Django 5.2.5 on 2025-11-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0026_remove_clinicvisit_follow_up_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='behaviorrecord',
            name='action_taken_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
