# Generated by Django 5.2.5 on 2025-11-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0027_behaviorrecord_action_taken_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicvisit',
            name='treatment_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
