# Generated by Django 5.2.5 on 2025-11-02 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0028_clinicvisit_treatment_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behaviorrecord',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='gradesettings',
            name='q3_open',
            field=models.BooleanField(default=False, help_text='Is Quarter 4 grade entry open for teachers?'),
        ),
    ]
