# Generated by Django 5.2.5 on 2025-11-03 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0029_alter_behaviorrecord_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('student', 'date')},
        ),
    ]
