# Generated by Django 5.2.5 on 2025-11-03 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0030_alter_attendancerecord_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('teacher_class', 'student', 'date')},
        ),
    ]
