# Generated by Django 5.2.5 on 2025-11-11 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0031_alter_attendancerecord_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_year', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Is this their current enrollment?')),
            ],
            options={
                'ordering': ['-school_year', 'student__last_name'],
            },
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='students_st_student_e7126a_idx',
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='students_st_grade_39b9da_idx',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_id',
            new_name='lrn',
        ),
        migrations.RemoveField(
            model_name='student',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='student',
            name='school_year',
        ),
        migrations.RemoveField(
            model_name='student',
            name='section',
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='is_finalized',
            field=models.BooleanField(default=False, help_text='If True, this grade record cannot be edited.'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='pre_final',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Calculated final rating', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='teacherclass',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'profile__role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='classes_taught', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sectionenrollment',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_enrollments', to='students.section'),
        ),
        migrations.AddField(
            model_name='sectionenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_enrollments', to='students.student'),
        ),
        migrations.AddField(
            model_name='student',
            name='historical_sections',
            field=models.ManyToManyField(related_name='enrolled_students', through='students.SectionEnrollment', to='students.section'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['lrn'], name='students_st_lrn_a0baca_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sectionenrollment',
            unique_together={('student', 'school_year')},
        ),
    ]
