# Generated by Django 5.2.5 on 2025-11-16 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0032_sectionenrollment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='teacher_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.teacherclass'),
        ),
    ]
