# Generated by Django 5.2.5 on 2025-11-17 14:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0033_alter_attendancerecord_teacher_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='lrn',
            field=models.CharField(db_index=True, max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='LRN must be exactly 12 digits and contain numbers only.', regex='^\\d{12}$')]),
        ),
    ]
